---
- include: user.yml
  when: user != 'vagrant'

- file: state=directory path={{ app_path }} owner={{ user }} group={{ user }}

- template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- include: deploy.yml
  sudo: yes
  sudo_user: "{{ user }}"
  when: user != 'vagrant'

- include: vagrant.yml
  sudo: no
  when: user == 'vagrant'
